services:
  # Service principal de base de données
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    expose:
      - "8080"
      - "5432"
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
      - "8080:8080"
    volumes:
      - data:/var/lib/postgresql/BRdata

  # Service principal Nakama
  nakama:
    build: .
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --config local.yml --database.address postgres:localdb@postgres:5432/nakama        
    expose:
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
    links:
      - "postgres:db"
    ports:
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped

  # Service de base de données pour le test
  postgres-test:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      - POSTGRES_DB=nakama_test
      - POSTGRES_PASSWORD=localdb
    expose:
      - "5433"
    image: postgres:12.2-alpine
    ports:
      - "5433:5432"
    volumes:
      - data-test:/var/lib/postgresql/BRdata_test

  # Service Nakama pour le test
  nakama-test:
    build: .
    depends_on:
      - postgres-test
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres-test:5432/nakama_test &&
        exec /nakama/nakama --config local-test.yml --database.address postgres:localdb@postgres-test:5432/nakama_test
    expose:
      - "7350"
      - "7353"
    ports:
      - "7353:7350"
      - "7354:7354"
    restart: unless-stopped

volumes:
  data:
  data-test:
