enum OpCodes {
    MATCH_START = 10,

    PLAYER_WAIT = 15,
    PLAYER_ATTACK = 20,
    PLAYER_USE_ITEM = 30,
    PLAYER_CHANGE_BLAST = 40,

    PLAYER_READY = 50,
    PLAYER_LEAVE = 51,
    ENEMY_READY = 55,

    NEW_BATTLE_TURN = 60,
    PLAYER_MUST_CHANGE_BLAST = 61,
    PLAYER_READY_MUST_CHANGE = 62,

    NEW_OFFER_TURN = 80,
    PLAYER_CHOOSE_OFFER = 81,
    
    NEW_BLAST = 90,

    MATCH_END = 100,
    OPPONENT_LEAVE = 101,

    ERROR_SERV = 404,

    DEBUG = 500,

}

